server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basecap_schema
    username: root
    password: 1234
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: root
    password: 1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true





  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update



logging:
  level:
    org:
      springframework:
        security: debug


